In [74]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import networkx as nx

import warnings
warnings.filterwarnings('ignore')

### Read network

In [75]:
# Load data
# First column is User ID while second column is Venue ID 
G_checkin = nx.read_edgelist('NYC_restaurant_checkin/edges.csv', delimiter=",")

In [42]:
nx.is_bipartite(G_checkin)

True

### Connected components in the network

In [59]:
# List connected components
[len(c) for c in sorted(nx.connected_components(G_checkin), key=len, reverse=True)]

[4906, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2]

We have one very large component and a few small. We choose to continue with the largest connected component.

In [68]:
largest_cc = max(nx.connected_components(G_checkin), key=len)
G = G_checkin.subgraph(largest_cc).copy()

### Projection

In [81]:
# Identify the bipartite sets
nodes = nx.algorithms.bipartite.basic.sets(G)
userID = nodes[0]
venueID = nodes[1]

In [83]:
# We want to project along venueID
len(venueID)

2861

In [107]:
# Non-square adjacency matrix
adjmat = nx.algorithms.bipartite.matrix.biadjacency_matrix(G_checkin, row_order=sorted(venueID))
print(adjmat.shape)

# Project along smaller axis
if adjmat.shape[0] == 2861:
   adjmat_proj = adjmat.dot(adjmat.T)
else:
   adjmat_proj = adjmat.T.dot(adjmat)

(2861, 2075)


In [113]:
for i in adjmat_proj.todense():
    print(i)

[[22  0  0 ...  0  0  0]]
[[0 1 0 ... 0 0 0]]
[[0 0 1 ... 0 0 0]]
[[0 0 0 ... 0 0 0]]
[[0 0 0 ... 0 0 0]]
[[0 0 0 ... 0 0 0]]
[[0 0 0 ... 0 0 0]]
[[0 0 0 ... 0 0 0]]
[[0 0 0 ... 0 0 0]]
[[0 0 0 ... 0 0 0]]
[[0 0 0 ... 0 0 0]]
[[0 0 0 ... 0 0 0]]
[[0 0 0 ... 0 0 0]]
[[0 0 0 ... 0 0 0]]
[[0 0 0 ... 0 0 0]]
[[0 0 0 ... 0 0 0]]
[[0 0 0 ... 0 0 0]]
[[0 0 0 ... 0 0 0]]
[[0 0 0 ... 0 0 0]]
[[0 0 0 ... 0 0 0]]
[[0 0 0 ... 0 0 0]]
[[0 0 0 ... 0 0 0]]
[[0 0 0 ... 0 0 0]]
[[1 0 0 ... 0 0 0]]
[[0 0 0 ... 1 0 0]]
[[0 0 0 ... 0 0 0]]
[[1 0 0 ... 1 0 0]]
[[0 0 0 ... 0 0 0]]
[[0 0 0 ... 0 0 0]]
[[0 0 0 ... 0 0 0]]
[[0 0 0 ... 0 0 0]]
[[0 0 0 ... 0 0 0]]
[[0 0 0 ... 0 0 0]]
[[0 0 0 ... 0 0 0]]
[[1 0 0 ... 0 0 0]]
[[0 0 0 ... 0 0 0]]
[[0 0 0 ... 0 0 0]]
[[0 0 0 ... 0 0 0]]
[[0 0 0 ... 0 0 0]]
[[0 0 0 ... 0 0 0]]
[[0 0 0 ... 0 0 0]]
[[0 0 0 ... 0 0 0]]
[[0 0 0 ... 0 0 0]]
[[0 0 0 ... 0 0 0]]
[[0 0 0 ... 0 0 0]]
[[0 0 0 ... 0 0 0]]
[[0 0 0 ... 0 0 0]]
[[0 0 0 ... 0 0 0]]
[[0 0 0 ... 0 0 0]]
[[0 0 0 ... 0 

In [114]:
# Export to csv
G_proj = nx.from_numpy_matrix(adjmat_proj)
nx.write_edgelist(G_proj, 'edgelist_simpleweights_proj.csv', comments='# source, target')

In [ ]:
# Stochastic adjacency matrix
# A / A.sum(axis = 1)
adjmat_proj_stch = adjmat_proj/adjmat_proj.sum(axis=1) # or (adj_matrix.T/adj_matrix.sum(axis=1)).T
adjmat_proj_stch.todense()